# config/packages/flysystem.yaml
flysystem:
    storages:
        backup.storage:
            adapter: 'ftp'
            options:
                host: 'ftp://transport.productsup.io/'
                username: 'pupDev'
                password: 'pupDev2018'
                port: 21
                root: ''
                passive: true
                ssl: false
                timeout: 30
                ignore_passive_address: ~
                utf8: false
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/default'